### ISSUE TITLE
empty output

### ISSUE THREAD

**Issue by Lnazvkl** [a8252525/detectron2_example_PCBdata#1]
hi, @a8252525 
I am trying to run your code with the dataset that you have used but after training (with 200 iter), when I want to test it can't find anything and the output is :
tensor([], dtype=torch.int64)
Boxes(tensor([], size=(0, 4)))
I really don't know how can I solve this.

**Comment by a8252525** [comment]
Did you try my colab on github?  I am still able to train and get the output on my colab.

**Comment by Lnazvkl** [comment]
No, I trained on my laptop but still, the output is empty.

**Comment by a8252525** [comment]
Can you find the difference between colab and your training process?

**Comment by Lnazvkl** [comment]
I am not training on colab, but on my system, I trained your code and dataset on cpu.
